services:
  whoami:
    image: traefik/whoami
    container_name: test-whoami
    networks:
      traefik:
    labels:
      traefik-proxy: true
      traefik.enable: true
      traefik.http.routers.whoami_https.rule: Host(`whoami.${DOMAIN_NAME}`)
      traefik.http.routers.whoami_https.entrypoints: websecure