name: whitelist-example

networks:
  proxy:
    external: true

services:
  dashboard:
    container_name: whitelist-example
    build: .
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.whitelist-example.rule: Host(`example.${DOMAIN}`)
      traefik.http.routers.whitelist-example.entrypoints: web
      traefik.http.routers.whitelist-example.middlewares: "security-headers@file"
      traefik.http.services.whitelist-example.loadbalancer.server.port: 80
