services:
  code:
    container_name: code
    image: codercom/code-server:latest
    restart: always
    environment:
      PASSWORD: ${CODE_PASSWORD}
      PUID: 1000
      GUID: 1000
    volumes:
      - $HOME/code-server/.local:/home/coder/.local
      - $HOME/code-server/.config:/home/coder/.config
      - $HOME/code-server/projects:/home/coder/project
    networks:
      traefik-tailscale:
    labels:
      traefik-tailscale: true
      traefik.enable: true
      traefik.http.routers.code.rule: Host(`code.ts.${DOMAIN_NAME}`)
      traefik.http.routers.code.entrypoints: websecure
      traefik.http.services.code.loadbalancer.server.port: 8080
