include:
  - services/tailscale/tailscale.docker-compose.yml
  - services/traefik-tailscale/traefik-tailscale.docker-compose.yml
  - services/traefik/traefik.docker-compose.yml
  - services/portainer/portainer.docker-compose.yml
  - services/home/home.docker-compose.yml
  - services/dashboard/dashboard.docker-compose.yml
  - services/code/code.docker-compose.yml

networks:
  traefik:
    name: traefik
    driver: bridge
  traefik-tailscale:
    name: traefik-tailscale
    driver: bridge