include:
  - services/tailscale/tailscale.docker-compose.yaml
  - services/traefik/traefik.docker-compose.yml
  - services/portainer/portainer.docker-compose.yml

networks:
  traefik:
    name: traefik
    driver: bridge