services:
  home:
    container_name: home
    build: .
    networks:
      traefik:
    labels:
      traefik-proxy: true
      traefik.enable: true
      traefik.http.routers.home.rule: Host(`${DOMAIN_NAME}`)
      traefik.http.routers.home.entrypoints: websecure
      traefik.http.services.home.loadbalancer.server.port: 80
