services:
  container_name: tailscale
  image: tailscale/tailscale:v1.84
  hostname: tailscale
  networks:
    traefik:
  environment:
    - TS_AUTHKEY=${TS_DOCKER_AUTH_KEY}
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_USERSPACE=false
  volumes:
    - tailscale:/var/lib/tailscale
  devices:
    - /dev/net/tun:/dev/net/tun
  cap_add:
    - net_admin
  restart: unless-stopped
  
volumes:
  tailscale: