api:
  dashboard: true
log:
  level: DEBUG
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
    constraints: "Label(`traefik-proxy`,`true`)"
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certresolver: dns-cloudflare
certificatesResolvers:
  dns-cloudflare:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /certs/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 90
global:
  checkNewVersion: true
  sendAnonymousUsage: false
