services:
  traefik:
    container_name: traefik
    image: traefik:v3.4
    restart: unless-stopped
    networks:
      traefik:
    ports:
      - "80:80"
      - "443:443"
    environment:
      CF_API_EMAIL: ${CLOUDFLARE_EMAIL}
      CF_DNS_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - traefik:/certs
    command:
      - --certificatesResolvers.dns-cloudflare.acme.email=${CLOUDFLARE_EMAIL}

volumes:
  traefik:
    name: traefik
