services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      traefik-tailscale:
    labels:
      traefik-tailscale: true
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`portainer.ts.${DOMAIN_NAME}`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.services.portainer.loadbalancer.server.port: 9000

volumes:
  portainer:
    name: portainer
