name: code

networks:
  proxy:
    external: true

services:
  code:
    container_name: code
    image: codercom/code-server:latest
    restart: always
    environment:
      PASSWORD: ${CODE_PASSWORD}
      DOMAIN: ${DOMAIN}
      PUID: 1000
      GUID: 1000
    volumes:
      - $HOME/code-server/.local:/home/coder/.local
      - $HOME/code-server/.config:/home/coder/.config
      - $HOME/code-server/projects:/home/coder/project
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.code.rule: Host(`code-private.${DOMAIN}`)
      traefik.http.routers.code.entrypoints: web
      traefik.http.routers.code.middlewares: security-headers@file
      traefik.http.services.code.loadbalancer.server.port: 8080
